### ISSUE TITLE
Functionality and difference in screenshot

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/using-svg-icons#1]
My markbot keeps saying that there is a big difference in my website vs example. Even tho it's with the same code...

@tthatkidmadrid

**Comment by thatkidmadrid** [comment]
can you please attach a screenshot of what markbot is complaning about for more context?

**Comment by askaalyy** [comment]
<img width="773" alt="Screen Shot 2021-10-30 at 5 36 21 PM" src="https://user-images.githubusercontent.com/74632728/139559086-ddf6161d-1e16-4b32-a281-e5d2c8d244d4.png">

**Comment by thatkidmadrid** [comment]
Your styles aren't showing up because you're referencing a stylesheet that doesn't exist. you're pointing to `master.css` but your file is called `main.css`. See `line 7` of your index.html

Here is a good checklist to use if ever you get stuck with something like this https://learn-the-web.algonquindesign.ca/topics/troubleshooting-checklist/

You would have caught the problem in the HTML part of the checklist! 😄

**Comment by askaalyy** [comment]
Ohh I missed that! got it, thank u!
